run file:
  R CMD BATCH {{file}}
  bat {{file}}out

run-pdf file:
	R CMD BATCH {{file}}
	okular Rplots.pdf &

rmarkdown file:
  Rscript -e "rmarkdown::render('{{file}}')"

watch file:
  inotifywait --monitor $(pwd)/{{file}} && echo "triggered" && Rscript -e "rmarkdown::render('{{file}}')"
  
  
