---
title: "Case Study 1 - Probability"
author: "Course 0165 - Group 7"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    fig_caption: yes
---

\thispagestyle{empty}

\begin{center}
  \vspace*{2cm}
  \Huge\textbf{Case Study 1 - Probability} \\[0.5cm]
  \Large\textbf{By example of Sports Team Selection Procedures} \\[1cm]
  \large
  \begin{tabular}{c}
    Benjamin Maixner \\
    Chirill Glitos \\
    Franziska Kirschner \\
    Said Rizvanov \\
  \end{tabular}
  \vfill
  \normalsize
  \textbf{Date}| `r Sys.Date()` |
\end{center}



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\newpage

# 1 Assembling the Team

The goal is to assemble a team of 5 athletes. The athletes are randomly picked from the available pool (6 from country A and 7 from country B). But there are certain conditions to be met each time. How the conditions will influence the success of our selection process is explored here.

### a) Exact Ratio

When selecting any 3 from country A and selecting any 2 from country B giving a split of 3 to 2:

\[
P(3A + 2B) = \frac{\binom{6}{3} * \binom{7}{2}}{\binom{13}{5}} = 0.\overline{326340} \approx 32.63\%
\]

### b) Just More

When there should just be more athletes of country B than from A. Necessitating athletes from B being more or equalt to 3:

\[
P(B > A) = P(B \geq 3) = \frac{\binom{7}{3}*\binom{6}{2} + \binom{7}{4}*\binom{6}{1} + \binom{7}{5}*\binom{6}{0}}{\binom{13}{5}} = 0.587412 \approx 58.74\%
\]

### c) At least 1

When there needs to be at least 1 athlete from country A we can equally exclude the option with no athlete from A:

\[
P(A \geq 1) = 1 - P(A = 0) = 1- \frac{\binom{7}{5}*\binom{6}{0}}{\binom{13}{5}} = 0.983682 \approx 98.37\%
\]

### d) Be Specific Please

When we need to select 1 specific athlete from country A (Alex) and country B (Bettina)\footnote{First character of names matching with the country name is purely coincidental}:

\[
P(\text{Alex} \cap \text{Bettina} \in \text{Team}) =\frac{\binom{11}{3}}{\binom{13}{5}} = \frac{165}{1287} \approx 12.82\%
\]

# 2 Basket or Foot?

The team is divided into basketball and football fans, where basketball fans always vote for the same TV channel and football fans may change their choice daily with a probability \( q \). We need to calculate the probability that any randomly selected member will vote the same way as the previous day.

Given:
\begin{itemize}
    \item Fraction \( p \) of the team are basketball fans who always vote the same.
    \item Fraction \( 1-p \) are football fans, and they change their choice with probability \( q \).
\end{itemize}

The probability that a basketball fan votes the same way again is 1 (since they never change), and the probability that a football fan votes the same way is \( 1-q \) (they vote differently with probability \( q \)).

Therefore, the overall probability that a member votes the same way as they did the previous time is calculated by weighing these probabilities by the proportion of each type of fan:

\[
P(\text{same}) = p + (1-p)(1-q)
\]

This formula provides the expected consistency in voting behavior across the team, considering the behavior patterns of both subgroups of fans.

# 3 Time to Perform

Each member of the team is supposed to supervise another during training. Who supervises who is supposed to be decided using a bowl and some paper. Each person will pick a random name from the bowl. Since self-supervision is mostly not working as well an athlete is not supposed to pick (and therefore supervise) himself.

The worst case would be each person picking their own name, then the whole operation was done for nothing!

\[
P(\text{Picking was useless}) = \frac{1}{5} * \frac{1}{4} * \frac{1}{3} * \frac{1}{2} * \frac{1}{1} = \frac{1}{120} = 0.008\overline{3333} = \approx 0.83\%
\]

# 4 Rinse and Repeate

Now we are tasked with creating a general model for this predicament. For larger $n$ the method of writing out the individual chances are impractical\footnote{Actually, even 5 fractions to type before was testing my patience}.

### a) Hurting Pinky

Now if we take a closer, lazier look at the last expression we will find a pattern which is strangely familiar. The factorial! This also saves the pinky from typing all these curly braces.

\[
... = \frac{1}{5} * \frac{1}{4} * \frac{1}{3} * \frac{1}{2} * \frac{1}{1} = \frac{1}{5 * 4 * 3 * 2 * 1} = \frac{1}{n!}
\]

### b) Favorite Athletes

Since we recognized that all athletes getting their own names in the selection procedure is quite rare we ask ourselves the question of a subset of athletes getting their own names back. The first $m$ athletes are supposed to be assigned other athletes. The rest ($n-m$) of the team we don't talk about...





