run file:
  R CMD BATCH {{file}}
  bat {{file}}out

run-pdf file:
	R CMD BATCH {{file}}
	okular Rplots.pdf &

rmd file:
  Rscript -e "rmarkdown::render('{{file}}')"

watch file:
  while inotifywait --m $(pwd)/{{file}} -re create,modify do just run {{file}} done
  
watch-rmd file:
  inotifywait --monitor $(pwd)/{{file}} && just rmd {{file}}
  
  
