name: Build and Verify R code

on:
  push:
    paths:
      - '**.Rmd'
  pull_request:
    paths:
      - '**.Rmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '10'

    - name: Set up Nix
      uses: cachix/install-nix-action@v14

    - name: Fetch Dependencies with Nix
      run: cd r && nix develop --extra-experimental-features nix-command --extra-experimental-features flakes

    - name: Build Rmd files
      run: sh gh_action.sh


    - uses: actions/upload-artifact@v4
      with:
        name: PDFs of Rmd Files
        if-no-files-found: warn
        path: |
          r/result/*
        retention-days: 10

        
